import { ReactNode } from 'react'
import './globals.css'
import { Roboto_Flex as Roboto, Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

export const metadata = {
  title: 'Gabriela Carniel Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} bg-gray-700 font-sans text-gray-100`}
      >
        {children}
      </body>
    </html>
  )
}
